---
- hosts: remote1
  tasks:

        - name: update apt
          become: yes
          apt:
             update_cache: yes


        - name: install ansible
          become: yes
          apt:
            name: ansible
            state: present
            update_cache: yes
